name: Team 5 workflow for git action new name

on:
    workflow_dispatch:

jobs:
    build_and_deploy_job:
        name: Build and deploy Job
        runs-on: ubuntu-latest
        steps:
            - name: test echo
              run: |
               echo 'log step 1'
            - name: define variable
              run: |
               echo 'I am a new step'

    I_am_a_new_job:
        name: trying to do a new job
        runs-on: ubuntu-latest
        steps:
            - name: Cowsays
              uses: mscoutermarsh/cowsays-action@master
              with:
                text: 'Moo!'
                color: 'red'

